# Generated by Django 5.2.6 on 2025-09-18 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passefacil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacaoQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=36)),
                ('data_validacao', models.DateTimeField(auto_now_add=True)),
                ('valido', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('passe_facil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='passefacil.passefacil')),
            ],
            options={
                'verbose_name': 'Validação de QR Code',
                'verbose_name_plural': 'Validações de QR Code',
                'ordering': ['-data_validacao'],
            },
        ),
    ]
