# Generated by Django 5.2.6 on 2025-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passefacil', '0002_validacaoqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passefacil',
            name='secret_totp',
            field=models.CharField(blank=True, help_text='Segredo para geração de códigos TOTP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passefacil',
            name='tentativas_validacao',
            field=models.PositiveIntegerField(default=0, help_text='Número de tentativas de validação'),
        ),
        migrations.AddField(
            model_name='passefacil',
            name='ultima_geracao',
            field=models.DateTimeField(blank=True, help_text='Data da última geração de código', null=True),
        ),
        migrations.AddField(
            model_name='passefacil',
            name='ultima_tentativa',
            field=models.DateTimeField(blank=True, help_text='Data da última tentativa de validação', null=True),
        ),
    ]
