# Generated by Django 5.2.6 on 2025-11-26 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passefacil', '0003_passefacil_secret_totp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacaoqrcode',
            name='data_validacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
