# Generated by Django 5.2.6 on 2025-10-12 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informativa'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('danger', 'Urgente')], default='info', max_length=10)),
                ('destinatarios', models.CharField(choices=[('todos', 'Todos os Usuários'), ('alunos', 'Apenas Alunos'), ('professores', 'Apenas Professores'), ('administradores', 'Apenas Administradores')], default='todos', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('erro', 'Erro no Envio')], default='pendente', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação Personalizada',
                'verbose_name_plural': 'Notificações Personalizadas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
