# Generated by Django 5.2.6 on 2025-10-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_personalizado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacaopersonalizada',
            name='destinatarios',
        ),
        migrations.RemoveField(
            model_name='notificacaopersonalizada',
            name='tipo',
        ),
    ]
