# Generated by Django 5.2.6 on 2025-11-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_personalizado', '0003_papelhistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(help_text='Ex: Email, Telefone, Endereço', max_length=50)),
                ('valor', models.CharField(help_text='Ex: contato@cop30.com.br, (81) 1234-5678', max_length=255)),
                ('icone', models.CharField(help_text='Classe do FontAwesome (ex: fa-solid fa-envelope)', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['ordem', 'tipo_contato'],
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('icone', models.CharField(help_text='Classe do FontAwesome (ex: fa-brands fa-twitter)', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
