# Generated by Django 4.2.10 on 2025-09-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_event_end_time'),
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_evento', to='agenda.event'),
        ),
    ]
