# Generated by Django 5.2.6 on 2025-10-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_notificacao_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('nivel', models.CharField(choices=[('info', 'Informativo'), ('alerta', 'Alerta'), ('critico', 'Crítico')], default='info', max_length=10, verbose_name='nível de importância')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='data de expiração')),
                ('fixo_no_topo', models.BooleanField(default=False, verbose_name='fixo no topo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_criados', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fixo_no_topo', '-data_criacao'],
            },
        ),
    ]
