# Generated by Django 5.2.6 on 2025-10-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0003_aviso"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacao",
            name="data_expiracao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data em que a notificação será considerada expirada",
                null=True,
                verbose_name="Data de Expiração",
            ),
        ),
    ]
