# Generated by Django 5.2.6 on 2025-11-22 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_backup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='lida',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='lida_em',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_sistema_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacao_usuario', to='notificacoes.notificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação do Usuário',
                'verbose_name_plural': 'Notificações dos Usuários',
                'unique_together': {('notificacao', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuarios',
            field=models.ManyToManyField(related_name='notificacoes', through='notificacoes.NotificacaoUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
