# Generated by Django 5.2.6 on 2025-09-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='nome completo'),
        ),
    ]
