# Generated by Django 5.2.6 on 2025-10-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('pode_gerenciar_eventos', 'Pode gerenciar eventos'), ('pode_visualizar_usuarios', 'Pode visualizar usuários'), ('pode_gerenciar_usuarios', 'Pode gerenciar usuários')], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('USUARIO', 'Usuário Comum'), ('EVENTOS', 'Usuário de Eventos'), ('GERENTE', 'Usuário Gerente'), ('SUPERUSER', 'Superusuário')], default='USUARIO', help_text='Nível de acesso do usuário no sistema', max_length=20, verbose_name='papel'),
        ),
    ]
