# Generated by Django 5.2.6 on 2025-10-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(blank=True, help_text='Sigla do estado (ex: SP, RJ)', max_length=2, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], default='N', max_length=1, null=True, verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='logradouro',
            field=models.CharField(blank=True, help_text='Nome da rua, avenida, etc.', max_length=255, null=True, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone_whatsapp',
            field=models.BooleanField(default=False, help_text='Este número tem WhatsApp?', verbose_name='WhatsApp?'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (00) 00000-0000', max_length=20, null=True, verbose_name='telefone'),
        ),
    ]
