# Generated by Django 5.2.5 on 2025-09-03 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="location",
            new_name="local",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="main_speakers",
            new_name="palestrantes",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="title",
            new_name="titulo",
        ),
        migrations.AlterUniqueTogether(
            name="useragenda",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="event",
            name="end_time",
        ),
        migrations.AddField(
            model_name="event",
            name="horario",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 9, 3, 4, 28, 6, 106843, tzinfo=datetime.timezone.utc
                ),
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
