# Generated by Django 4.2.23 on 2025-09-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_location_event_local_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='event',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do evento', null=True, verbose_name='Descrição'),
        ),
    ]
