# Generated by Django 5.2.6 on 2025-09-12 23:38

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_event_options_event_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragenda',
            options={'verbose_name': 'Agenda do Usuário', 'verbose_name_plural': 'Agendas dos Usuários'},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora do Evento'),
        ),
        migrations.AlterUniqueTogether(
            name='useragenda',
            unique_together={('user', 'event')},
        ),
    ]
