# Generated by Django 5.2.6 on 2025-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0005_event_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
