# Generated by Django 5.2.6 on 2025-10-17 05:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_event_latitude_event_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='palestrantes',
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='event',
            name='importante',
            field=models.BooleanField(default=False, verbose_name='Evento Importante'),
        ),
        migrations.AddField(
            model_name='event',
            name='palestrante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Palestrante'),
        ),
        migrations.AlterField(
            model_name='event',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 17, 6, 32, 37, 726008, tzinfo=datetime.timezone.utc), verbose_name='Data e Hora de Término'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.CharField(max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 17, 5, 33, 8, 282051, tzinfo=datetime.timezone.utc), verbose_name='Data e Hora de Início'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(default='sustentabilidade', max_length=100, verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='UserAgenda',
        ),
    ]
