# Generated by Django 5.2.5 on 2025-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0006_event_latitude_event_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="importante",
            field=models.BooleanField(
                default=False, help_text="Marque se este evento é importante"
            ),
        ),
    ]
