"""
Django settings for sga_cop_30 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#i+mjii)++-mb_gvdmirus@5k2b-1^1na(3#7j%i49_2_@5@78"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Adicione seu domínio do PythonAnywhere aos hosts permitidos
ALLOWED_HOSTS = [
    'joaovcc.pythonanywhere.com',
    'www.joaovcc.pythonanywhere.com',
    '127.0.0.1',  # Para desenvolvimento local
    'localhost',   # Para desenvolvimento local
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core.apps.CoreConfig',
    'apps.usuarios.apps.UsuariosConfig',
    'apps.agenda.apps.AgendaConfig',
    'apps.notificacoes.apps.NotificacoesConfig',
    'apps.passefacil.apps.PassefacilConfig',
    'apps.admin_personalizado.apps.AdminPersonalizadoConfig',
    'django_bootstrap5',
    'rest_framework',
]

# Configuração do modelo de usuário personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

# Configurações de autenticação
LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'home'  # Página para redirecionar após o login
LOGOUT_REDIRECT_URL = 'home'  # Página para redirecionar após o logout

# Configuração para redirecionar usuários não autenticados para a página de login
LOGIN_EXEMPT_URLS = [
    r'^$',  # Página inicial
    r'^agenda/$',  # Página da agenda oficial
    r'^usuarios/login/$',  # Página de login
    r'^usuarios/registrar/$',  # Página de registro
    r'^usuarios/password_reset/',  # URLs de redefinição de senha
    r'^static/.*$',  # Arquivos estáticos
]

# Aplicativos que não requerem autenticação
LOGIN_EXEMPT_APPS = [
    'django.contrib.auth',
    'django.contrib.staticfiles',
]

# Configurações de sessão
SESSION_COOKIE_AGE = 1209600  # 2 semanas em segundos
SESSION_SAVE_EVERY_REQUEST = True  # Renova a sessão a cada requisição

# Configurações do Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    }
}

# Configurações de autenticação padrão do Django

# Configurações de senha
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configurações de email
# Modo de desenvolvimento: exibe emails no console
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Configurações de produção (substitua com suas configurações de email reais)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'  # Ou outro servidor SMTP
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'seu-email@gmail.com'  # Substitua pelo seu email
    EMAIL_HOST_PASSWORD = 'sua-senha'  # Substitua pela sua senha

# Configurações de redefinição de senha
PASSWORD_RESET_TIMEOUT = 14400  # 4 horas em segundos
DEFAULT_FROM_EMAIL = 'noreply@sgacop30.com'  # Email padrão para envio
EMAIL_SUBJECT_PREFIX = '[SGA COP 30] '  # Prefixo para assuntos de email

# OneSignal / Push settings (configure via environment variables on PythonAnywhere)
ONESIGNAL_APP_ID = os.environ.get('ONESIGNAL_APP_ID', '')
ONESIGNAL_REST_API_KEY = os.environ.get('ONESIGNAL_REST_API_KEY', '')
# Public base URL of the site (used to build absolute links in push notifications)
SITE_URL = os.environ.get('SITE_URL', 'https://SEU-DOMINIO.pythonanywhere.com')

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "sga_cop_30.middleware.LoginRequiredMiddleware",
]

ROOT_URLCONF = "sga_cop_30.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'apps/admin_personalizado/templates'),
            # ou
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Expose OneSignal App ID to templates
                'apps.core.context_processors.onesignal',
                # Avisos ativos para templates
                'apps.notificacoes.context_processors.avisos_ativos',
            ],
        },
    },
]

WSGI_APPLICATION = "sga_cop_30.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Onde os arquivos estáticos serão coletados

# Configurações adicionais para arquivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Pasta global de arquivos estáticos
]

# Isso deve estar fora do INSTALLED_APPS
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
# Configurações de arquivos de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Tamanho máximo de upload (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CSRF_TRUSTED_ORIGINS = [
    'https://joaovcc.pythonanywhere.com',
    'https://www.joaovcc.pythonanywhere.com',
]
GOOGLE_MAPS_API_KEY = 'AIzaSyC59hMjc_tTFXtLwCILXphKzW5BvuZPTQk'
